server:
  ingress:
    enabled: true
    hosts:
      - host: drone.MINIKUBE_IP.nip.io
        paths:
          - path: /
            pathType: ImplementationSpecific

  env:
    DRONE_SERVER_HOST: drone.MINIKUBE_IP.nip.io
    DRONE_SERVER_PROTO: http
    DRONE_DATABASE_DRIVER: postgres
    DRONE_GITEA_SERVER: http://gitea.MINIKUBE_IP.nip.io

  secrets:
    # openssl rand -hex 16
    DRONE_DATABASE_SECRET: a1501fdf503fbbdda9e736c1b020b8fc
    DRONE_DATABASE_DATASOURCE: "postgres://postgres:postgres@postgres-service:5432/postgres?sslmode=disable"
    # DRONE_GITEA_CLIENT_ID: 6a6e252b-8bad-4aeb-9178-ee8ed6b84150
    # DRONE_GITEA_CLIENT_SECRET: RyJ3hmG2A4Q2MDMEO433qIkokbpR7QjEodxHTylMV7xj
    DRONE_USER_CREATE: "username:testuser,admin:true"
    DRONE_USER_FILTER: testuser
