log:
  level: debug

image:
  repository: burakince/n8n-python
  pullPolicy: Never
  tag: N8N_VERSION

db:
  type: postgresdb

nodes:
  builtin:
    enabled: true
    modules:
      - crypto
      - fs
      - http
      - https
      - querystring
      - url
  external:
    reinstallMissingPackages: true
    packages:
      - "iconv-lite@0.6.3"
      - "n8n-nodes-python@0.1.4"
      - "n8n-nodes-chatwoot@0.1.40"

main:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 512Mi

  extraEnvVars:
    N8N_SECURE_COOKIE: "false"

worker:
  mode: queue

  count: 1
  autoscaling:
    enabled: false

  resources:
    requests:
      cpu: 1000m
      memory: 250Mi
    limits:
      cpu: 2000m
      memory: 2Gi

ingress:
  enabled: true
  hosts:
    - host: n8n.MINIKUBE_IP.nip.io
      paths:
        - path: /
          pathType: Prefix

webhook:
  mode: queue
  url: "https://webhook.MINIKUBE_IP.nip.io"

  count: 1
  autoscaling:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 512Mi

postgresql:
  enabled: true

redis:
  enabled: true