apiVersion: v1
kind: Pod
metadata:
  name: azure-cli
  namespace: default
spec:
  containers:
  - name: azure-cli
    image: mcr.microsoft.com/azure-cli:latest
    command:
    - "/bin/sh"
    - "-c"
    - |
      az storage container create -n mlflow
      az storage container show -n mlflow
      exit $?
    env:
    - name: AZURE_STORAGE_CONNECTION_STRING
      value: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite-service:10000/devstoreaccount1;QueueEndpoint=http://azurite-service:10001/devstoreaccount1"
  restartPolicy: Never
