apiVersion: v1
kind: Service
metadata:
  name: azurite-service
  namespace: default
  labels:
    app: azurite
spec:
  type: NodePort
  ports:
    - name: blob
      port: 10000
      targetPort: 10000
      nodePort: 31000
    - name: queue
      port: 10001
      targetPort: 10001
      nodePort: 31001
  selector:
    app: azurite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: default
  labels:
    app: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: "mcr.microsoft.com/azure-storage/azurite:3.16.0"
          imagePullPolicy: IfNotPresent
          command:
          - azurite
          - -l
          - /data
          - --blobHost
          - 0.0.0.0
          - --queueHost
          - 0.0.0.0
          - --loose
          ports:
            - name: blob
              containerPort: 10000
              protocol: TCP
            - name: queue
              containerPort: 10001
              protocol: TCP
