apiVersion: v1
kind: Service
metadata:
  name: fake-gcs-service
  namespace: default
  labels:
    app: fake-gcs
spec:
  type: ClusterIP
  ports:
    - name: fake-gcs
      port: 4443
  selector:
    app: fake-gcs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-gcs
  namespace: default
  labels:
    app: fake-gcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-gcs
  template:
    metadata:
      labels:
        app: fake-gcs
    spec:
      containers:
        - name: fake-gcs
          image: "fsouza/fake-gcs-server:1.37.10"
          imagePullPolicy: IfNotPresent
          command:
          - "/bin/sh"
          - "-c"
          - |
            mkdir -p /data/mlflow
            /bin/fake-gcs-server -data /data -scheme http
          ports:
            - name: fake-gcs
              containerPort: 4443
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-gcs-ingress
  namespace: default
spec:
  rules:
  - host: "gcs.MINIKUBE_IP.nip.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: fake-gcs-service
            port:
              number: 4443
