apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - name: minio
      port: 9000
    - name: minio-console
      port: 9001
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: default
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "minio/minio:RELEASE.2022-04-12T06-55-35Z"
          imagePullPolicy: IfNotPresent
          command:
          - "/bin/sh"
          - "-c"
          - |
            set -x
            mkdir -p /data/mlflow
            minio server /data --console-address ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
          ports:
            - name: minio
              containerPort: 9000
              protocol: TCP
            - name: minio-console
              containerPort: 9001
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: default
spec:
  rules:
  - host: "minio-dashboard.MINIKUBE_IP.nip.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-service
            port:
              number: 9001
  - host: "minio.MINIKUBE_IP.nip.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-service
            port:
              number: 9000