apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: default
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_USER
              value: mlflow
            - name: MYSQL_PASSWORD
              value: mlflow
            - name: MYSQL_ROOT_PASSWORD
              value: mlflow
            - name: MYSQL_DATABASE
              value: mlflow
            - name: MYSQL_TCP_PORT
              value: "3306"
          ports:
            - name: mysqldb
              containerPort: 3306
