log:
  level: warn

db:
  type: postgresdb

main:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 512Mi
  extraEnvVars:
    N8N_SECURE_COOKIE: "false"

worker:
  mode: queue

  autoscaling:
    enabled: true

  resources:
    requests:
      cpu: 1000m
      memory: 250Mi
    limits:
      cpu: 2000m
      memory: 2Gi

ingress:
  enabled: true
  hosts:
    - host: n8n.MINIKUBE_IP.nip.io
      paths:
        - path: /
          pathType: Prefix

webhook:
  mode: queue
  url: "https://webhook.MINIKUBE_IP.nip.io"

  autoscaling:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 512Mi

postgresql:
  enabled: true

redis:
  enabled: true