log:
  level: debug

ingress:
  enabled: true
  hosts:
    - host: mlflow.MINIKUBE_IP.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: mlflow-postgres-postgresql.mlflow.svc.cluster.local
    port: 5432
    database: mlflow_db
    user: mlflow
    password: mlflow

artifactRoot:
  proxiedArtifactStorage: true
  s3:
    enabled: true
    bucket: mlflow
    awsAccessKeyId: admin
    awsSecretAccessKey: password

extraArgs:
  workers: "4"
  gunicornOpts: "--timeout=120"

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://minio.mlflow.svc.cluster.local:9000
