apiVersion: v1
kind: Pod
metadata:
  name: model-training
  namespace: mlflow
spec:
  restartPolicy: Never
  containers:
    - name: model-training
      image: python:3.13
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "500m"
          memory: "512Mi"
      command:
      - "/bin/sh"
      - "-c"
      - |
        curl https://raw.githubusercontent.com/mlflow/mlflow/master/examples/sklearn_elasticnet_wine/train.py --output train.py
        pip install pandas numpy scikit-learn mlflow
        python train.py
      env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow.mlflow.svc.cluster.local:5000
